services:
  localstack:
    image: "public.ecr.aws/localstack/localstack:3.7.0"
    restart: always
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - LS_LOG=trace
      - SERVICES=s3
